######################################################################
# Automatically generated by qmake (2.00a) Mon Sep 25 16:00:56 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += -g -std=c++0x -rdynamic -Wall
QMAKE_LFLAGS += -g -rdynamic -Wall

# Input
HEADERS += src/*.h 
SOURCES += src/*.cpp

QT += xml network
CONFIG += console
